name: MineChat
main: com.rodusek.minechat.MineChat
version: 0.0.2
author: Bitwize
description: Minecraft Chat Management Plugin
softdepend: [Vault,PermissionsEx, bPermissions]


# Note: both commands and their associated permissions 
# are all managed programmatically